title: Francesco Leopardi
logo: "/images/profile_pic1.png"
description: |
  Francesco Leopardi is an undergraduate student at Boston University studying Economics and Data Science. 
  He is originally from Italy but has moved various times between Italy, Switzerland, Saudi Arabia, and the USA.\n
  
  
  Feel free to reach out at either tel: +1 (857) 867-9840 or email: leopardi@bu.edu.\n
  
  Skills:
    - Data Analysis \n
    - Microsoft Office\n
    - GSuite \n
    - SQL \n
    - R Programming Language\n
    - Python\n
    - English\n
    - Italian\n
    - Spanish\n
    - German\n
    - Arabic\n

  <a href="https://www.linkedin.com/in/francesco-leopardi-1ba6351a3/">View My LinkedIn Profile</a> \n
  <a href="https://github.com/frangi2002">View My GitHub Profile</a> \n
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
