title: Francesco Leopardi # your name (or website title) here
logo: "/images/profile_pic.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br>Francesco Leopardi is an undergraduate studenta at Boston University studying Economics and Data Science. He is originally from Italy but has moved various times between Italy, Switzerland, Saudi Arabia, and the USA. <br> Feel free to reach out at either tel: +1 (857) 867-9840 or email:leopardi@bu.edu<br>
  Second description 
  <br>  ###Skills <br>
        -Data Analysis
        -Microsoft Office
        -GSuite
        -SQL
        -R Programming Language
        -Python
        -Structured Thinking
        -Group Wrok
        -English
        -Italian
        -Spanish
        -German
        -Arabic
 <br>
  <a href="https://www.linkedin.com/in/francesco-leopardi-1ba6351a3/">View My LinkedIn Profile</a>
  <a href="https://github.com/frangi2002">View My GitHub Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
